### ISSUE TITLE
Problem with Areas

### ISSUE THREAD

**Issue by huwred** [kasparboelkjeldsen/Knowit.Umbraco.InstantBlockPreview#11]
I am trying to access Areas when in preview mode, but it always retirns an empty array.

I'm trying to do `var areas =(Umbraco.Cms.Core.Models.Blocks.BlockGridArea[])Model.Areas`

**Comment by kasparboelkjeldsen** [comment]
Thanks for the pull request to fix this.

**Comment by huwred** [comment]
No problem, thought I may as well take a look since I'm trying it out 😄 This was the only bit missing for me
