### ISSUE TITLE
New version 2.1.2 odd rendering

### ISSUE THREAD

**Issue by huwred** [kasparboelkjeldsen/Knowit.Umbraco.InstantBlockPreview#13]
The latest version appears to be duplicating content.

**2.1.1**
![image](https://github.com/user-attachments/assets/60adc894-a2c7-45d1-a280-2e125a5a7020)

**2.1.2**
![image](https://github.com/user-attachments/assets/6196eda6-ad45-4cdc-a9e3-9df151fcfc9c)

**Comment by huwred** [comment]
looks like it is related to my change. Will try and figure out why.

**Comment by huwred** [comment]
I think probably best to revert my change and I'll try a different way of getting what I need.

**Comment by kasparboelkjeldsen** [comment]
@huwred I think I'd like to see some code, because I can't replicate.
![image](https://github.com/user-attachments/assets/9af4660b-e3b0-4581-8ec2-eab1f053d289)

This is on a fresh Umbraco 14 with 2 elementtypes available in the grid, a "Paragraph" element and a "AreaTest" element.

I've even installed 2.1.2 through nuget instead of linking up projects to make sure.

This is the code for both of them 

AreaTest: 

```razor
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem>

<div>
    @await Html.GetBlockGridItemAreasHtmlAsync(Model)
    @ViewBag.renderGridAreaSlots
</div>
```

and Paragraph

```razor
@using Umbraco.Cms.Core.Models.Blocks
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<BlockGridItem<Paragraph>>

<div>
    @Model.Content.Text    
</div>
```

Running with minimal config to enable areas

```json
"Knowit.Umbraco.InstantBlockPreview": {
  "areaReplace": true
}
```

**Comment by huwred** [comment]
I'll take another look today

**Comment by huwred** [comment]
actually, it doesn't appear to be my template, the issue occurs if you reload the page after saving it

![image](https://github.com/user-attachments/assets/a6945742-5279-48e4-b9e4-ff92b3fd93f6)

My view
```@{
    var backgroundColor = Model.Settings.BackgroundColour;
    var noBackgroundColor = String.IsNullOrEmpty(backgroundColor);
    var hasBrightContrast = Model.Settings.Contrast == "#ffffff";
    var cssClass = Model.Settings?.SectionClass;
}

@if (ViewBag.blockPreview != null)
{
    <section class="@cssClass" style="background-color: @backgroundColor"
    @(noBackgroundColor ? "nobackgroundcolor" : "")
    @(hasBrightContrast ? "bright-contrast" : "")>
        @await Html.GetBlockGridItemAreasHtmlAsync(Model)
        @ViewBag.renderGridAreaSlots
    </section>
}```

**Comment by kasparboelkjeldsen** [comment]
@huwred issue seems to be that you somehow succesfully get  @await Html.GetBlockGridItemAreasHtmlAsync(Model) rendered through my api when I don't, so you get both the rendered output and the injection of area-slots I put in at  @ViewBag.renderGridAreaSlots

I'm trying to figure out how to replicate, but for now you should be able to fix it for you with just removing the  @await Html.GetBlockGridItemAreasHtmlAsync(Model) line from the code you run in the backoffice. It's not needed as I'm building the areas needed in place of @ViewBag.renderGridAreaSlots

**Comment by huwred** [comment]
cool, that fixed it. I'm wondering then if my original issue is because of this way of building the areas. My inital template is like below, but assume it doesn't work because I am rendering individual areas here. So would need an @ViewBag.renderGridAreaSlot rather than @ViewBag.renderGridAreaSlots methodology

```
@{
    var backgroundColor = Model.Settings.BackgroundColour;
    var noBackgroundColor = String.IsNullOrEmpty(backgroundColor);
    var hasBrightContrast = Model.Settings.Contrast == "#ffffff";
    var cssClass = Model.Settings?.SectionClass;
    var rightColSpan = ((Umbraco.Cms.Core.Models.Blocks.BlockGridArea[])Model.Areas)[1].ColumnSpan;
    var leftAlias = ((Umbraco.Cms.Core.Models.Blocks.BlockGridArea[])Model.Areas)[0].Alias;
    var rightAlias = ((Umbraco.Cms.Core.Models.Blocks.BlockGridArea[])Model.Areas)[1].Alias;

}
<div class="row @cssClass" style="background-color: @backgroundColor"
@(noBackgroundColor ? "nobackgroundcolor" : "")
@(hasBrightContrast ? "bright-contrast" : "")>
    <div class="leftcol col rounded-6 p-3 m-2" data-area-alias="@leftAlias">
        @await Html.GetBlockGridItemAreaHtmlAsync(Model, leftAlias)
    </div>
    <div class="rightcol col-12 col-sm-@rightColSpan  rounded-6 p-3 m-2" data-area-alias="@rightAlias">
        @await Html.GetBlockGridItemAreaHtmlAsync(Model, rightAlias)
    </div>

</div>
```

**Comment by kasparboelkjeldsen** [comment]
I'll look into it, because I might as well expose more injections since the whole deal with this package in contrast to Rick Butterfields version is configurability and customization. 

If it's not too tricky I'll see about adding it for v2.2, but happy you have a solution for now.

**Comment by huwred** [comment]
I've found another issue with desirialisation, so will make new issue for that
