### ISSUE TITLE
Problem with checkbox lists

### ISSUE THREAD

**Issue by huwred** [kasparboelkjeldsen/Knowit.Umbraco.InstantBlockPreview#14]
I have a block which contains a simple checkboxlist called Version , when the template gets hit in preview mode it does not serialise the checboxlist property, it displays an error.

![image](https://github.com/user-attachments/assets/585342ed-1fc7-4490-bb24-50d405032f14)

**Comment by kasparboelkjeldsen** [comment]
@huwred taking a look at this today :)
