### ISSUE TITLE
Issue with MultUrl Picker

### ISSUE THREAD

**Issue by huwred** [kasparboelkjeldsen/Knowit.Umbraco.InstantBlockPreview#15]
I have a block that contains a multiUrl picker, in preview mode the property is null so the preview html fails.

This is my View, Model.Content.Link is always null

```
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<CallToActionBlock>>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    var link = Model.Content.Link;
    if (link is null)
    {
        return;
    }
}

<a class="call-to-action" href="@link.Url" target="@link.Target">@link.Name</a>
```

**Comment by kasparboelkjeldsen** [comment]
@huwred taking a look at this today :)

**Comment by kasparboelkjeldsen** [comment]
Go ahead and give 2.1.5 a spin :)

**Comment by huwred** [comment]
Looks great 👍 both issues now displaying

![image](https://github.com/user-attachments/assets/d1e34f98-6c1f-419b-9fdc-640647b8c901)

checbox list and Link
