### ISSUE TITLE
Config request

### ISSUE THREAD

**Issue by huwred** [kasparboelkjeldsen/Knowit.Umbraco.InstantBlockPreview#17]
In your client script you set the border around your div

`<div style="border: 1px solid var(--uui-color-border,#d8d7d9); min-height: 50px; box-sizing: border-box;">`

Any chance this could be configurable? looks neater without the border

**Comment by kasparboelkjeldsen** [comment]
@huwred "our" styling has now been moved to a class and [Anna Dalsgaard](https://github.com/Adals-01) has added the "divInlineStyle" configuration property that allows you to add an inline style to the "frame" of the element. So you can override what we do in the class.

**Comment by huwred** [comment]
Cool, will have a look in a day or so, busy settling in to our new Spanish home
