### ISSUE TITLE
Support for RichTextBlockItem

### ISSUE THREAD

**Issue by robertjf** [kasparboelkjeldsen/Knowit.Umbraco.InstantBlockPreview#6]
With the support for Content Blocks in the RichText Editor, it would be great to be able to have this supported as well. For reference, see here:

https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/rte-blocks

**Comment by kasparboelkjeldsen** [comment]
Excellent suggestion, I'll look into that now that I'm back from holidays.

**Comment by kasparboelkjeldsen** [comment]
@robertjf alright so this will have to wait until more stuff is working on Umbracos end. It does not look like Umbraco 13, or 14.1 treats the blocks in the RTE as blocks in blocklist or blockgrid - ie. it doesn't let you do anything with it. Also blocks in RTE are not doing well in 13.4 right now https://github.com/umbraco/Umbraco-CMS/issues/15516

**Comment by kasparboelkjeldsen** [comment]
@robertjf here you go - RTE support in 1.0.6 - doesn't seem possible for Umbraco 14 yet - will implement when possible.

https://www.nuget.org/packages/Knowit.Umbraco.InstantBlockPreview/1.0.6
