### ISSUE TITLE
Support for custom stylesheets

### ISSUE THREAD

**Issue by royws** [kasparboelkjeldsen/Knowit.Umbraco.InstantBlockPreview#8]
Hi,

I was trying out your package in Umbraco V14, it works wonderfully!  I was wondering if there's any support for adding custom stylesheets to blocklist blocks, this was possible before in older Umbraco versions within the blocklist settings (these settings appear to be gone).

**Comment by kasparboelkjeldsen** [comment]
You can use the Injections setting to add a stylesheet. It basically just lets you prepend lines of code to whatever is outputted, so a 

"Knowit.Umbraco.InstantBlockPreview": {
  "injections": ["<link rel=\"stylesheet\" href=\"yourstyle.css\">"]
}

should do it.

**Comment by royws** [comment]
Thanks, that works great.
